URI = "neo4j+ssc://ed1c30a6.databases.neo4j.io"
AUTH = ("neo4j", "oKK1MbR-c02pVRlgfClC1VQn0qgL-o99SrNP42LfKdQ")
OPENAI_KEY = "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"
